//
//  Image+Icons.swift
//  
//
//  Created by Carlo on 1/17/22.
//

import SwiftUI

@available(iOS 13.0.0, *)

extension SurgeUI {

    public struct Image {
        /* Font Awesome Free Regular Icons */
        public static let address_book: SwiftUI.Image = SwiftUI.Image("address-book", bundle: .module)
        public static let address_card: SwiftUI.Image = SwiftUI.Image("address-card", bundle: .module)
        public static let angry: SwiftUI.Image = SwiftUI.Image("angry", bundle: .module)
        public static let arrow_alt_circle_down: SwiftUI.Image = SwiftUI.Image("arrow-alt-circle-down", bundle: .module)
        public static let arrow_alt_circle_left: SwiftUI.Image = SwiftUI.Image("arrow-alt-circle-left", bundle: .module)
        public static let arrow_alt_circle_right: SwiftUI.Image = SwiftUI.Image("arrow-alt-circle-right", bundle: .module)
        public static let arrow_alt_circle_up: SwiftUI.Image = SwiftUI.Image("arrow-alt-circle-up", bundle: .module)
        public static let bell_slash: SwiftUI.Image = SwiftUI.Image("bell-slash", bundle: .module)
        public static let bell: SwiftUI.Image = SwiftUI.Image("bell", bundle: .module)
        public static let bookmark: SwiftUI.Image = SwiftUI.Image("bookmark", bundle: .module)
        public static let building: SwiftUI.Image = SwiftUI.Image("building", bundle: .module)
        public static let calendar_alt: SwiftUI.Image = SwiftUI.Image("calendar-alt", bundle: .module)
        public static let calendar_check: SwiftUI.Image = SwiftUI.Image("calendar-check", bundle: .module)
        public static let calendar_minus: SwiftUI.Image = SwiftUI.Image("calendar-minus", bundle: .module)
        public static let calendar_plus: SwiftUI.Image = SwiftUI.Image("calendar-plus", bundle: .module)
        public static let calendar_times: SwiftUI.Image = SwiftUI.Image("calendar-times", bundle: .module)
        public static let calendar: SwiftUI.Image = SwiftUI.Image("calendar", bundle: .module)
        public static let caret_square_down: SwiftUI.Image = SwiftUI.Image("caret-square-down", bundle: .module)
        public static let caret_square_left: SwiftUI.Image = SwiftUI.Image("caret-square-left", bundle: .module)
        public static let caret_square_right: SwiftUI.Image = SwiftUI.Image("caret-square-right", bundle: .module)
        public static let caret_square_up: SwiftUI.Image = SwiftUI.Image("caret-square-up", bundle: .module)
        public static let chart_bar: SwiftUI.Image = SwiftUI.Image("chart-bar", bundle: .module)
        public static let check_circle: SwiftUI.Image = SwiftUI.Image("check-circle", bundle: .module)
        public static let check_square: SwiftUI.Image = SwiftUI.Image("check-square", bundle: .module)
        public static let circle: SwiftUI.Image = SwiftUI.Image("circle", bundle: .module)
        public static let clipboard: SwiftUI.Image = SwiftUI.Image("clipboard", bundle: .module)
        public static let clock: SwiftUI.Image = SwiftUI.Image("clock", bundle: .module)
        public static let clone: SwiftUI.Image = SwiftUI.Image("clone", bundle: .module)
        public static let closed_captioning: SwiftUI.Image = SwiftUI.Image("closed-captioning", bundle: .module)
        public static let comment_alt: SwiftUI.Image = SwiftUI.Image("comment-alt", bundle: .module)
        public static let comment_dots: SwiftUI.Image = SwiftUI.Image("comment-dots", bundle: .module)
        public static let comment: SwiftUI.Image = SwiftUI.Image("comment", bundle: .module)
        public static let comments: SwiftUI.Image = SwiftUI.Image("comments", bundle: .module)
        public static let compass: SwiftUI.Image = SwiftUI.Image("compass", bundle: .module)
        public static let copy: SwiftUI.Image = SwiftUI.Image("copy", bundle: .module)
        public static let copyright: SwiftUI.Image = SwiftUI.Image("copyright", bundle: .module)
        public static let credit_card: SwiftUI.Image = SwiftUI.Image("credit-card", bundle: .module)
        public static let dizzy: SwiftUI.Image = SwiftUI.Image("dizzy", bundle: .module)
        public static let dot_circle: SwiftUI.Image = SwiftUI.Image("dot-circle", bundle: .module)
        public static let edit: SwiftUI.Image = SwiftUI.Image("edit", bundle: .module)
        public static let envelope_open: SwiftUI.Image = SwiftUI.Image("envelope-open", bundle: .module)
        public static let envelope: SwiftUI.Image = SwiftUI.Image("envelope", bundle: .module)
        public static let eye_slash: SwiftUI.Image = SwiftUI.Image("eye-slash", bundle: .module)
        public static let eye: SwiftUI.Image = SwiftUI.Image("eye", bundle: .module)
        public static let file_alt: SwiftUI.Image = SwiftUI.Image("file-alt", bundle: .module)
        public static let file_archive: SwiftUI.Image = SwiftUI.Image("file-archive", bundle: .module)
        public static let file_audio: SwiftUI.Image = SwiftUI.Image("file-audio", bundle: .module)
        public static let file_code: SwiftUI.Image = SwiftUI.Image("file-code", bundle: .module)
        public static let file_excel: SwiftUI.Image = SwiftUI.Image("file-excel", bundle: .module)
        public static let file_image: SwiftUI.Image = SwiftUI.Image("file-image", bundle: .module)
        public static let file_pdf: SwiftUI.Image = SwiftUI.Image("file-pdf", bundle: .module)
        public static let file_powerpoint: SwiftUI.Image = SwiftUI.Image("file-powerpoint", bundle: .module)
        public static let file_video: SwiftUI.Image = SwiftUI.Image("file-video", bundle: .module)
        public static let file_word: SwiftUI.Image = SwiftUI.Image("file-word", bundle: .module)
        public static let file: SwiftUI.Image = SwiftUI.Image("file", bundle: .module)
        public static let flag: SwiftUI.Image = SwiftUI.Image("flag", bundle: .module)
        public static let flushed: SwiftUI.Image = SwiftUI.Image("flushed", bundle: .module)
        public static let folder_open: SwiftUI.Image = SwiftUI.Image("folder-open", bundle: .module)
        public static let folder: SwiftUI.Image = SwiftUI.Image("folder", bundle: .module)
        public static let font_awesome_logo_full: SwiftUI.Image = SwiftUI.Image("font-awesome-logo-full", bundle: .module)
        public static let frown_open: SwiftUI.Image = SwiftUI.Image("frown-open", bundle: .module)
        public static let frown: SwiftUI.Image = SwiftUI.Image("frown", bundle: .module)
        public static let futbol: SwiftUI.Image = SwiftUI.Image("futbol", bundle: .module)
        public static let gem: SwiftUI.Image = SwiftUI.Image("gem", bundle: .module)
        public static let grimace: SwiftUI.Image = SwiftUI.Image("grimace", bundle: .module)
        public static let grin_alt: SwiftUI.Image = SwiftUI.Image("grin-alt", bundle: .module)
        public static let grin_beam_sweat: SwiftUI.Image = SwiftUI.Image("grin-beam-sweat", bundle: .module)
        public static let grin_beam: SwiftUI.Image = SwiftUI.Image("grin-beam", bundle: .module)
        public static let grin_hearts: SwiftUI.Image = SwiftUI.Image("grin-hearts", bundle: .module)
        public static let grin_squint_tears: SwiftUI.Image = SwiftUI.Image("grin-squint-tears", bundle: .module)
        public static let grin_squint: SwiftUI.Image = SwiftUI.Image("grin-squint", bundle: .module)
        public static let grin_stars: SwiftUI.Image = SwiftUI.Image("grin-stars", bundle: .module)
        public static let grin_tears: SwiftUI.Image = SwiftUI.Image("grin-tears", bundle: .module)
        public static let grin_tongue_squint: SwiftUI.Image = SwiftUI.Image("grin-tongue-squint", bundle: .module)
        public static let grin_tongue_wink: SwiftUI.Image = SwiftUI.Image("grin-tongue-wink", bundle: .module)
        public static let grin_tongue: SwiftUI.Image = SwiftUI.Image("grin-tongue", bundle: .module)
        public static let grin_wink: SwiftUI.Image = SwiftUI.Image("grin-wink", bundle: .module)
        public static let grin: SwiftUI.Image = SwiftUI.Image("grin", bundle: .module)
        public static let hand_lizard: SwiftUI.Image = SwiftUI.Image("hand-lizard", bundle: .module)
        public static let hand_paper: SwiftUI.Image = SwiftUI.Image("hand-paper", bundle: .module)
        public static let hand_peace: SwiftUI.Image = SwiftUI.Image("hand-peace", bundle: .module)
        public static let hand_point_down: SwiftUI.Image = SwiftUI.Image("hand-point-down", bundle: .module)
        public static let hand_point_left: SwiftUI.Image = SwiftUI.Image("hand-point-left", bundle: .module)
        public static let hand_point_right: SwiftUI.Image = SwiftUI.Image("hand-point-right", bundle: .module)
        public static let hand_point_up: SwiftUI.Image = SwiftUI.Image("hand-point-up", bundle: .module)
        public static let hand_pointer: SwiftUI.Image = SwiftUI.Image("hand-pointer", bundle: .module)
        public static let hand_rock: SwiftUI.Image = SwiftUI.Image("hand-rock", bundle: .module)
        public static let hand_scissors: SwiftUI.Image = SwiftUI.Image("hand-scissors", bundle: .module)
        public static let hand_spock: SwiftUI.Image = SwiftUI.Image("hand-spock", bundle: .module)
        public static let handshake: SwiftUI.Image = SwiftUI.Image("handshake", bundle: .module)
        public static let hdd: SwiftUI.Image = SwiftUI.Image("hdd", bundle: .module)
        public static let heart: SwiftUI.Image = SwiftUI.Image("heart", bundle: .module)
        public static let hospital: SwiftUI.Image = SwiftUI.Image("hospital", bundle: .module)
        public static let hourglass: SwiftUI.Image = SwiftUI.Image("hourglass", bundle: .module)
        public static let id_badge: SwiftUI.Image = SwiftUI.Image("id-badge", bundle: .module)
        public static let id_card: SwiftUI.Image = SwiftUI.Image("id-card", bundle: .module)
        public static let image: SwiftUI.Image = SwiftUI.Image("image", bundle: .module)
        public static let images: SwiftUI.Image = SwiftUI.Image("images", bundle: .module)
        public static let keyboard: SwiftUI.Image = SwiftUI.Image("keyboard", bundle: .module)
        public static let kiss_beam: SwiftUI.Image = SwiftUI.Image("kiss-beam", bundle: .module)
        public static let kiss_wink_heart: SwiftUI.Image = SwiftUI.Image("kiss-wink-heart", bundle: .module)
        public static let kiss: SwiftUI.Image = SwiftUI.Image("kiss", bundle: .module)
        public static let laugh_beam: SwiftUI.Image = SwiftUI.Image("laugh-beam", bundle: .module)
        public static let laugh_squint: SwiftUI.Image = SwiftUI.Image("laugh-squint", bundle: .module)
        public static let laugh_wink: SwiftUI.Image = SwiftUI.Image("laugh-wink", bundle: .module)
        public static let laugh: SwiftUI.Image = SwiftUI.Image("laugh", bundle: .module)
        public static let lemon: SwiftUI.Image = SwiftUI.Image("lemon", bundle: .module)
        public static let life_ring: SwiftUI.Image = SwiftUI.Image("life-ring", bundle: .module)
        public static let lightbulb: SwiftUI.Image = SwiftUI.Image("lightbulb", bundle: .module)
        public static let list_alt: SwiftUI.Image = SwiftUI.Image("list-alt", bundle: .module)
        public static let map: SwiftUI.Image = SwiftUI.Image("map", bundle: .module)
        public static let meh_blank: SwiftUI.Image = SwiftUI.Image("meh-blank", bundle: .module)
        public static let meh_rolling_eyes: SwiftUI.Image = SwiftUI.Image("meh-rolling-eyes", bundle: .module)
        public static let meh: SwiftUI.Image = SwiftUI.Image("meh", bundle: .module)
        public static let minus_square: SwiftUI.Image = SwiftUI.Image("minus-square", bundle: .module)
        public static let money_bill_alt: SwiftUI.Image = SwiftUI.Image("money-bill-alt", bundle: .module)
        public static let moon: SwiftUI.Image = SwiftUI.Image("moon", bundle: .module)
        public static let newspaper: SwiftUI.Image = SwiftUI.Image("newspaper", bundle: .module)
        public static let object_group: SwiftUI.Image = SwiftUI.Image("object-group", bundle: .module)
        public static let object_ungroup: SwiftUI.Image = SwiftUI.Image("object-ungroup", bundle: .module)
        public static let paper_plane: SwiftUI.Image = SwiftUI.Image("paper-plane", bundle: .module)
        public static let pause_circle: SwiftUI.Image = SwiftUI.Image("pause-circle", bundle: .module)
        public static let play_circle: SwiftUI.Image = SwiftUI.Image("play-circle", bundle: .module)
        public static let plus_square: SwiftUI.Image = SwiftUI.Image("plus-square", bundle: .module)
        public static let question_circle: SwiftUI.Image = SwiftUI.Image("question-circle", bundle: .module)
        public static let registered: SwiftUI.Image = SwiftUI.Image("registered", bundle: .module)
        public static let sad_cry: SwiftUI.Image = SwiftUI.Image("sad-cry", bundle: .module)
        public static let sad_tear: SwiftUI.Image = SwiftUI.Image("sad-tear", bundle: .module)
        public static let save: SwiftUI.Image = SwiftUI.Image("save", bundle: .module)
        public static let share_square: SwiftUI.Image = SwiftUI.Image("share-square", bundle: .module)
        public static let smile_beam: SwiftUI.Image = SwiftUI.Image("smile-beam", bundle: .module)
        public static let smile_wink: SwiftUI.Image = SwiftUI.Image("smile-wink", bundle: .module)
        public static let smile: SwiftUI.Image = SwiftUI.Image("smile", bundle: .module)
        public static let snowflake: SwiftUI.Image = SwiftUI.Image("snowflake", bundle: .module)
        public static let square: SwiftUI.Image = SwiftUI.Image("square", bundle: .module)
        public static let star_half: SwiftUI.Image = SwiftUI.Image("star-half", bundle: .module)
        public static let star: SwiftUI.Image = SwiftUI.Image("star", bundle: .module)
        public static let sticky_note: SwiftUI.Image = SwiftUI.Image("sticky-note", bundle: .module)
        public static let stop_circle: SwiftUI.Image = SwiftUI.Image("stop-circle", bundle: .module)
        public static let sun: SwiftUI.Image = SwiftUI.Image("sun", bundle: .module)
        public static let surprise: SwiftUI.Image = SwiftUI.Image("surprise", bundle: .module)
        public static let thumbs_down: SwiftUI.Image = SwiftUI.Image("thumbs-down", bundle: .module)
        public static let thumbs_up: SwiftUI.Image = SwiftUI.Image("thumbs-up", bundle: .module)
        public static let times_circle: SwiftUI.Image = SwiftUI.Image("times-circle", bundle: .module)
        public static let tired: SwiftUI.Image = SwiftUI.Image("tired", bundle: .module)
        public static let trash_alt: SwiftUI.Image = SwiftUI.Image("trash-alt", bundle: .module)
        public static let user_circle: SwiftUI.Image = SwiftUI.Image("user-circle", bundle: .module)
        public static let user: SwiftUI.Image = SwiftUI.Image("user", bundle: .module)
        public static let window_close: SwiftUI.Image = SwiftUI.Image("window-close", bundle: .module)
        public static let window_maximize: SwiftUI.Image = SwiftUI.Image("window-maximize", bundle: .module)
        public static let window_minimize: SwiftUI.Image = SwiftUI.Image("window-minimize", bundle: .module)
        public static let window_restore: SwiftUI.Image = SwiftUI.Image("window-restore", bundle: .module)
        
        public init(){
        }
    }
}
